export * as help from './help.js'
export * as tpa from '../tpa/chatCommand.js'
export * as tm from '../bank/chatCommand.js'
export * as sharehome from '../home/chatCommand.js'
export * as getmenu from '../menu/chatCommand.js'
export * as rtp from '../rtp/chatCommand.js'
export * as back from '../back/chatCommand.js'